/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package billing;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author dell laptop
 */
public class Billingsystem extends javax.swing.JFrame {

    String opreations;
    String answers;
    double firstnum,secondnum,results;
    /**
     * Creates new form Billingsystem
     */
    public Billingsystem() {
        initComponents();
        super.setTitle("Smart billing System");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtdisplay = new javax.swing.JTextField();
        badd = new javax.swing.JButton();
        bsubs = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        bmultiply = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b0 = new javax.swing.JButton();
        bdot = new javax.swing.JButton();
        bper = new javax.swing.JButton();
        bdiv = new javax.swing.JButton();
        bclear = new javax.swing.JButton();
        bequal = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        Buttonallcalculate = new javax.swing.JButton();
        buttonclearall = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setPreferredSize(new java.awt.Dimension(330, 360));
        jPanel1.setLayout(null);

        txtdisplay.setEditable(false);
        txtdisplay.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jPanel1.add(txtdisplay);
        txtdisplay.setBounds(20, 20, 290, 60);

        badd.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        badd.setText("+");
        badd.setPreferredSize(new java.awt.Dimension(60, 50));
        badd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baddActionPerformed(evt);
            }
        });
        jPanel1.add(badd);
        badd.setBounds(250, 100, 60, 50);

        bsubs.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        bsubs.setText("-");
        bsubs.setPreferredSize(new java.awt.Dimension(60, 50));
        bsubs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsubsActionPerformed(evt);
            }
        });
        jPanel1.add(bsubs);
        bsubs.setBounds(250, 160, 60, 50);

        b6.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        b6.setText("6");
        b6.setPreferredSize(new java.awt.Dimension(60, 50));
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        jPanel1.add(b6);
        b6.setBounds(180, 160, 60, 50);

        b5.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        b5.setText("5");
        b5.setPreferredSize(new java.awt.Dimension(60, 50));
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        jPanel1.add(b5);
        b5.setBounds(90, 160, 60, 50);

        b4.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        b4.setText("4");
        b4.setPreferredSize(new java.awt.Dimension(60, 50));
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        jPanel1.add(b4);
        b4.setBounds(20, 160, 60, 50);

        bmultiply.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        bmultiply.setText("*");
        bmultiply.setPreferredSize(new java.awt.Dimension(60, 50));
        bmultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmultiplyActionPerformed(evt);
            }
        });
        jPanel1.add(bmultiply);
        bmultiply.setBounds(250, 220, 60, 50);

        b3.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        b3.setText("3");
        b3.setPreferredSize(new java.awt.Dimension(60, 50));
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        jPanel1.add(b3);
        b3.setBounds(180, 220, 60, 50);

        b2.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        b2.setText("2");
        b2.setPreferredSize(new java.awt.Dimension(60, 50));
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        jPanel1.add(b2);
        b2.setBounds(90, 220, 60, 50);

        b1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        b1.setText("1");
        b1.setPreferredSize(new java.awt.Dimension(60, 50));
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel1.add(b1);
        b1.setBounds(20, 220, 60, 50);

        b0.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        b0.setText("0");
        b0.setPreferredSize(new java.awt.Dimension(60, 50));
        b0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b0ActionPerformed(evt);
            }
        });
        jPanel1.add(b0);
        b0.setBounds(20, 280, 60, 50);

        bdot.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        bdot.setText(".");
        bdot.setPreferredSize(new java.awt.Dimension(60, 50));
        bdot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdotActionPerformed(evt);
            }
        });
        jPanel1.add(bdot);
        bdot.setBounds(90, 280, 60, 50);

        bper.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        bper.setText("%");
        bper.setPreferredSize(new java.awt.Dimension(60, 50));
        bper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bperActionPerformed(evt);
            }
        });
        jPanel1.add(bper);
        bper.setBounds(180, 280, 60, 50);

        bdiv.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        bdiv.setText("/");
        bdiv.setPreferredSize(new java.awt.Dimension(60, 50));
        bdiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdivActionPerformed(evt);
            }
        });
        jPanel1.add(bdiv);
        bdiv.setBounds(250, 280, 60, 50);

        bclear.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        bclear.setText("CLEAR");
        bclear.setPreferredSize(new java.awt.Dimension(60, 50));
        bclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bclearActionPerformed(evt);
            }
        });
        jPanel1.add(bclear);
        bclear.setBounds(20, 340, 130, 50);

        bequal.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        bequal.setText("=");
        bequal.setPreferredSize(new java.awt.Dimension(60, 50));
        bequal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bequalActionPerformed(evt);
            }
        });
        jPanel1.add(bequal);
        bequal.setBounds(180, 340, 120, 50);

        b7.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        b7.setText("7");
        b7.setPreferredSize(new java.awt.Dimension(60, 50));
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        jPanel1.add(b7);
        b7.setBounds(20, 100, 60, 50);

        b8.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        b8.setText("8");
        b8.setPreferredSize(new java.awt.Dimension(60, 50));
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });
        jPanel1.add(b8);
        b8.setBounds(90, 100, 60, 50);

        b9.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        b9.setText("9");
        b9.setPreferredSize(new java.awt.Dimension(60, 50));
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });
        jPanel1.add(b9);
        b9.setBounds(180, 100, 60, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(250, 110, 330, 400);

        jPanel3.setBackground(new java.awt.Color(51, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setPreferredSize(new java.awt.Dimension(930, 370));
        jPanel3.setLayout(null);

        jCheckBox1.setBackground(new java.awt.Color(0, 153, 204));
        jCheckBox1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jCheckBox1.setText("Biscuits");
        jCheckBox1.setPreferredSize(new java.awt.Dimension(130, 49));
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel3.add(jCheckBox1);
        jCheckBox1.setBounds(20, 260, 150, 49);

        jCheckBox2.setBackground(new java.awt.Color(0, 153, 204));
        jCheckBox2.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jCheckBox2.setText("Wafers");
        jCheckBox2.setPreferredSize(new java.awt.Dimension(130, 49));
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jPanel3.add(jCheckBox2);
        jCheckBox2.setBounds(20, 200, 139, 49);

        jCheckBox3.setBackground(new java.awt.Color(0, 153, 204));
        jCheckBox3.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jCheckBox3.setText("Pizza");
        jCheckBox3.setPreferredSize(new java.awt.Dimension(130, 49));
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        jPanel3.add(jCheckBox3);
        jCheckBox3.setBounds(20, 140, 110, 49);

        jCheckBox4.setBackground(new java.awt.Color(0, 153, 204));
        jCheckBox4.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jCheckBox4.setText("Books");
        jCheckBox4.setPreferredSize(new java.awt.Dimension(130, 49));
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });
        jPanel3.add(jCheckBox4);
        jCheckBox4.setBounds(20, 80, 120, 49);

        jCheckBox6.setBackground(new java.awt.Color(0, 153, 204));
        jCheckBox6.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jCheckBox6.setText("Fruits");
        jCheckBox6.setPreferredSize(new java.awt.Dimension(130, 49));
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });
        jPanel3.add(jCheckBox6);
        jCheckBox6.setBounds(20, 20, 120, 49);

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("0");
        jPanel3.add(jTextField1);
        jTextField1.setBounds(180, 270, 80, 30);

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("0");
        jPanel3.add(jTextField2);
        jTextField2.setBounds(180, 210, 80, 30);

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("0");
        jPanel3.add(jTextField3);
        jTextField3.setBounds(180, 150, 80, 30);

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("0");
        jPanel3.add(jTextField4);
        jTextField4.setBounds(180, 90, 80, 30);

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("0");
        jPanel3.add(jTextField5);
        jTextField5.setBounds(180, 30, 80, 30);

        jPanel4.setBackground(new java.awt.Color(255, 255, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jLabel1.setText("SGST");
        jLabel1.setPreferredSize(new java.awt.Dimension(150, 43));
        jPanel4.add(jLabel1);
        jLabel1.setBounds(20, 260, 150, 45);

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jLabel2.setText("CGST");
        jLabel2.setPreferredSize(new java.awt.Dimension(150, 43));
        jPanel4.add(jLabel2);
        jLabel2.setBounds(20, 210, 150, 45);

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jLabel4.setText("Total Cost of Mileage");
        jLabel4.setPreferredSize(new java.awt.Dimension(150, 43));
        jPanel4.add(jLabel4);
        jLabel4.setBounds(20, 140, 350, 45);

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jLabel5.setText("Total Delivery Cost");
        jLabel5.setPreferredSize(new java.awt.Dimension(150, 43));
        jPanel4.add(jLabel5);
        jLabel5.setBounds(20, 70, 320, 45);

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jLabel6.setText("Total Cost of Item");
        jLabel6.setPreferredSize(new java.awt.Dimension(150, 43));
        jPanel4.add(jLabel6);
        jLabel6.setBounds(20, 10, 300, 45);

        jTextField6.setEditable(false);
        jTextField6.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setText("0");
        jTextField6.setPreferredSize(new java.awt.Dimension(40, 50));
        jPanel4.add(jTextField6);
        jTextField6.setBounds(380, 270, 130, 40);

        jTextField7.setEditable(false);
        jTextField7.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField7.setText("0");
        jTextField7.setPreferredSize(new java.awt.Dimension(40, 50));
        jPanel4.add(jTextField7);
        jTextField7.setBounds(380, 220, 130, 40);

        jTextField8.setEditable(false);
        jTextField8.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField8.setText("0");
        jTextField8.setPreferredSize(new java.awt.Dimension(40, 50));
        jPanel4.add(jTextField8);
        jTextField8.setBounds(380, 150, 130, 40);

        jTextField10.setEditable(false);
        jTextField10.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField10.setText("0");
        jTextField10.setPreferredSize(new java.awt.Dimension(40, 50));
        jPanel4.add(jTextField10);
        jTextField10.setBounds(380, 80, 130, 40);

        jTextField11.setEditable(false);
        jTextField11.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jTextField11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField11.setText("0");
        jTextField11.setPreferredSize(new java.awt.Dimension(40, 50));
        jPanel4.add(jTextField11);
        jTextField11.setBounds(380, 20, 130, 40);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(290, 30, 540, 340);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(590, 110, 870, 390);

        jPanel5.setBackground(new java.awt.Color(255, 51, 51));
        jPanel5.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel5.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jLabel3.setText("Tax");
        jPanel5.add(jLabel3);
        jLabel3.setBounds(30, 80, 61, 43);

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jLabel7.setText("Total Amount");
        jPanel5.add(jLabel7);
        jLabel7.setBounds(30, 140, 228, 43);

        jLabel8.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jLabel8.setText("Sab Total");
        jPanel5.add(jLabel8);
        jLabel8.setBounds(30, 20, 160, 43);

        jTextField9.setEditable(false);
        jTextField9.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField9.setText("Rs: 0.00");
        jPanel5.add(jTextField9);
        jTextField9.setBounds(390, 80, 240, 49);

        jTextField12.setEditable(false);
        jTextField12.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jTextField12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField12.setText("Rs: 0.00");
        jPanel5.add(jTextField12);
        jTextField12.setBounds(390, 140, 240, 49);

        jTextField13.setEditable(false);
        jTextField13.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jTextField13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField13.setText("Rs: 0.00");
        jPanel5.add(jTextField13);
        jTextField13.setBounds(390, 20, 240, 49);

        Buttonallcalculate.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        Buttonallcalculate.setText("Calculate");
        Buttonallcalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonallcalculateActionPerformed(evt);
            }
        });
        jPanel5.add(Buttonallcalculate);
        Buttonallcalculate.setBounds(810, 110, 310, 51);

        buttonclearall.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        buttonclearall.setText("Clear");
        buttonclearall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonclearallActionPerformed(evt);
            }
        });
        jPanel5.add(buttonclearall);
        buttonclearall.setBounds(810, 40, 310, 51);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(250, 530, 1210, 220);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 204));
        jLabel9.setText("Smart Billing System");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(640, 10, 460, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b0ActionPerformed
        String Enternumber=txtdisplay.getText()+b0.getText();
        txtdisplay.setText(Enternumber);
    }//GEN-LAST:event_b0ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
          String Enternumber=txtdisplay.getText()+b1.getText();
        txtdisplay.setText(Enternumber);
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
         String Enternumber=txtdisplay.getText()+b2.getText();
        txtdisplay.setText(Enternumber);
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
           String Enternumber=txtdisplay.getText()+b3.getText();
        txtdisplay.setText(Enternumber);
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
           String Enternumber=txtdisplay.getText()+b4.getText();
        txtdisplay.setText(Enternumber);
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
         String Enternumber=txtdisplay.getText()+b5.getText();
        txtdisplay.setText(Enternumber);
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
         String Enternumber=txtdisplay.getText()+b6.getText();
        txtdisplay.setText(Enternumber);
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
          String Enternumber=txtdisplay.getText()+b7.getText();
        txtdisplay.setText(Enternumber);
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
           String Enternumber=txtdisplay.getText()+b8.getText();
        txtdisplay.setText(Enternumber);
    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
          String Enternumber=txtdisplay.getText()+b9.getText();
        txtdisplay.setText(Enternumber);
    }//GEN-LAST:event_b9ActionPerformed

    private void bdotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdotActionPerformed
        if(!txtdisplay.getText().contains("."))
        {
            txtdisplay.setText(txtdisplay.getText()+bdot.getText());
        }
    }//GEN-LAST:event_bdotActionPerformed

    private void baddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baddActionPerformed
       firstnum=Double.parseDouble(txtdisplay.getText());
       txtdisplay.setText("");
       opreations="+";
    }//GEN-LAST:event_baddActionPerformed

    private void bsubsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsubsActionPerformed
          firstnum=Double.parseDouble(txtdisplay.getText());
       txtdisplay.setText("");
       opreations="-";
    }//GEN-LAST:event_bsubsActionPerformed

    private void bmultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmultiplyActionPerformed
         firstnum=Double.parseDouble(txtdisplay.getText());
       txtdisplay.setText("");
       opreations="*";
    }//GEN-LAST:event_bmultiplyActionPerformed

    private void bdivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdivActionPerformed
          firstnum=Double.parseDouble(txtdisplay.getText());
       txtdisplay.setText("");
       opreations="/";
    }//GEN-LAST:event_bdivActionPerformed

    private void bperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bperActionPerformed
        firstnum=Double.parseDouble(txtdisplay.getText());
       txtdisplay.setText("");
       opreations="%";
    }//GEN-LAST:event_bperActionPerformed

    private void bclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bclearActionPerformed
     txtdisplay.setText("");
    }//GEN-LAST:event_bclearActionPerformed

    private void bequalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bequalActionPerformed
        secondnum=Double.parseDouble(txtdisplay.getText());
        
        if(opreations =="+")
        {
            results=firstnum+secondnum;
            answers=String.format("%.2f",results);
            txtdisplay.setText(answers);
        
        }
        else if(opreations=="-")
        {
            results=firstnum-secondnum;
            answers=String.format("%.2f",results);
            txtdisplay.setText(answers);
        
        }
          else if(opreations=="*")
        {
            results=firstnum*secondnum;
            answers=String.format("%.2f",results);
            txtdisplay.setText(answers);
        
        }
         else if(opreations=="/")
        {
            results=firstnum/secondnum;
            answers=String.format("%.2f",results);
            txtdisplay.setText(answers);
        
        }
         else 
         {
              results=firstnum%secondnum;
            answers=String.format("%.2f",results);
            txtdisplay.setText(answers);
         }
                
    }//GEN-LAST:event_bequalActionPerformed

    private void buttonclearallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonclearallActionPerformed
      txtdisplay.setText("");
      jTextField5.setText("0");
      jTextField4.setText("0");
      jTextField3.setText("0");
      jTextField2.setText("0");
      jTextField1.setText("0");
      jTextField11.setText("0");
      jTextField10.setText("0");
      jTextField8.setText("0");
      jTextField7.setText("0");
      jTextField6.setText("0");
      jTextField13.setText("Rs. 0.00");
      jTextField9.setText("Rs. 0.0");
      jTextField12.setText("Rs. 0.00");
      
      
      jCheckBox6.setSelected(false);
     jCheckBox4.setSelected(false);
     jCheckBox3.setSelected(false);
     jCheckBox2.setSelected(false);
     jCheckBox1.setSelected(false);
    }//GEN-LAST:event_buttonclearallActionPerformed

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
          if(jCheckBox6.isSelected())
          {
             jTextField5.setEditable(true);
             jTextField5.setText(" ");
             jTextField5.requestFocus();
          }
          else
          {
              jTextField5.setEditable(false);
              jTextField5.setText("0");
          }
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
                if(jCheckBox4.isSelected())
          {
             jTextField4.setEditable(true);
             jTextField4.setText(" ");
             jTextField4.requestFocus();
          }
          else
          {
              jTextField4.setEditable(false);
              jTextField4.setText("0");
          }
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
         if(jCheckBox3.isSelected())
          {
             jTextField3.setEditable(true);
             jTextField3.setText(" ");
             jTextField3.requestFocus();
          }
          else
          {
              jTextField3.setEditable(false);
              jTextField3.setText("0");
          }
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
         if(jCheckBox2.isSelected())
          {
             jTextField2.setEditable(true);
             jTextField2.setText(" ");
             jTextField2.requestFocus();
          }
          else
          {
              jTextField2.setEditable(false);
              jTextField2.setText("0");
          }
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
         if(jCheckBox1.isSelected())
          {
             jTextField1.setEditable(true);
             jTextField1.setText(" ");
             jTextField1.requestFocus();
          }
          else
          {
              jTextField1.setEditable(false);
              jTextField1.setText("0");
          }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void ButtonallcalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonallcalculateActionPerformed
       if((jCheckBox6.isSelected()) || (jCheckBox4.isSelected()) || (jCheckBox3.isSelected()) || (jCheckBox2.isSelected()) || (jCheckBox1.isSelected()))
       {
           double f=Double.parseDouble(jTextField5.getText()) * 50;
           double book=Double.parseDouble(jTextField4.getText()) * 150;
           double p=Double.parseDouble(jTextField3.getText()) * 99;
           double w=Double.parseDouble(jTextField2.getText()) * 10;
           double b=Double.parseDouble(jTextField1.getText()) *20;
           
           double totalitem=f+book+p+w+b;
           double del=totalitem * 5/100;
           double mil=del *5/100;
           
           double subtotal=totalitem+del+mil;
           double cgst=subtotal *9/100;
           double sgst=cgst;
           
           double tax=cgst+sgst;
           double amount=subtotal+tax;
           
           String item=String.format("%.2f",totalitem);
           jTextField11.setText((String)item);
           
             String delivery=String.format("%.2f",del);
           jTextField10.setText((String)delivery);
           
             String milege=String.format("%.2f",mil);
           jTextField8.setText((String)milege);
           
             String cg=String.format("%.2f",cgst);
           jTextField7.setText((String)cg);
           
             String sg=String.format("%.2f",sgst);
           jTextField6.setText((String)sg);
                   
           
             String sub1=String.format("%.2f",subtotal);
           jTextField13.setText((String)sub1);
           
             String taxx=String.format("%.2f",tax);
           jTextField9.setText((String)taxx);
           
             String finalamount=String.format("%.2f",amount);
           jTextField12.setText((String)finalamount);
           
       }
       else
       {
           txtdisplay.setText("select any");
       }
    }//GEN-LAST:event_ButtonallcalculateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            /* Set the Nimbus look and feel */
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
            
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
            * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
            */
          
            //</editor-fold>
            
            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new Billingsystem().setVisible(true);
                }
            });
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Billingsystem.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Billingsystem.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Billingsystem.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Billingsystem.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buttonallcalculate;
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton badd;
    private javax.swing.JButton bclear;
    private javax.swing.JButton bdiv;
    private javax.swing.JButton bdot;
    private javax.swing.JButton bequal;
    private javax.swing.JButton bmultiply;
    private javax.swing.JButton bper;
    private javax.swing.JButton bsubs;
    private javax.swing.JButton buttonclearall;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField txtdisplay;
    // End of variables declaration//GEN-END:variables
}
